.\" $Header: idle.man,v 1.3 88/11/19 14:55:56 saka Exp $ University of Library and Information Science
.TH IDLE 1 "17 October 1988"
.SH NAME
idle \- display idling
.SH SYNOPSIS
.B idle
[ options ]
.SH DESCRIPTION
.I Idle
は作業中にしばらく席を外すとき、
ディスプレイの焼きつきを防止しつつ作業の途中であることを
表示するものです。
.PP
この
.I idle
は
.I X
window system version
.I 10
.I (X10)
が動作しているディスプレイでは
ビットマップで、
それ以外の場合
.I (TTY)
は
.I "curses(3X)"
パッケージを用いてキャラクタで
表示を行ないます。
.PP
.I Idle
は次のオプションを解釈します。
.TP 12
.B \-X
.I X
window 
.I (X10)
モードの指定。
ビットマップ・アイコン表示による
.I idle
.I (DISPLAY
環境変数がセットされているときのデフォルト)。
.TP
.B \-T
キャラクタ・ターミナル
.I (TTY)
モードの指定。
キャラクタ・アイコン表示による
.I idle
.I (DISPLAY
環境変数がセットされていないときのデフォルト)。
.TP
.B \-b
スクリーン・ブランク・モードの指定。何も表示しない。
.TP
.B \-m
ムービング・アイコン・モードの指定。
アイコンが2秒おきに移動する(デフォルト)。
.TP
.BI \-F " color"
フォア・グランド・カラーの指定(デフォルトは白)。
.I (X10
モード、カラーディスプレイのみ。)
.TP
.BI \-B " color"
バック・グランド・カラーの指定(デフォルトは黒)。
.I (X10
モード、カラーディスプレイのみ。)
.TP
.B \-r
リバース・カラーの指定
.I (X10
モードのみ)。
.TP
.BI \-i " string"
アイコンとなるビットマップ・ファイルの名前
.I (X10
モード)/文字列
.I (TTY
モード)の指定。
.TP
.BI \-D " display"
.I X10
のディスプレイの指定
.I (X10
モードのみ)。
.PP
.I Idle
はキーボードかマウスのボタン
.I (X10
モードのみ)が押されれば即座に解除します。
.PP
.I color
および
.I display
の指定は
.I X10
の形式に準拠しています。
また、アイコンは
.I TTY
モードでは指定した
.I string
自身が用いられ、
.I X10
モードでは
.I string
をファイル名として
.I "bitmap(1)"
で作成された形式のビットマップ・ファイルを
読み込みアイコンとして用います。
.SH AUTHOR
阪口哲男(図書館情報大学)	E-mail: saka@ulis.JUNET
.SH BUGS
.I TTY
モードの場合は２秒毎に画面の書き換えが行なわれるため、
.I w(1)
などにおける
.B idle
時間が表示されません。
